# Find FFTW3
#
# FFTW3_INCLUDE_DIR
# FFTW3_LIBRARY
# FFTW3_FOUND
#

FIND_PATH(FFTW3_INCLUDE_DIR NAMES fftw3.h)

FIND_LIBRARY(FFTW3_LIBRARY NAMES fftw3)

IF(FFTW3_INCLUDE_DIR AND FFTW3_LIBRARY)
	SET(FFTW3_FOUND TRUE)
ENDIF(FFTW3_INCLUDE_DIR AND FFTW3_LIBRARY)

IF(FFTW3_FOUND)
	IF(NOT FFTW3_FIND_QUIETLY)
		MESSAGE(STATUS "Found fftw3: -I${FFTW3_INCLUDE_DIR}, ${FFTW3_LIBRARY}")
	ENDIF(NOT FFTW3_FIND_QUIETLY)
ELSE(FFTW3_FOUND)
	IF(FFTW3_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find fftw3")
	ENDIF(FFTW3_FIND_REQUIRED)
ENDIF(FFTW3_FOUND)
